### ISSUE TITLE
Remove the use of list elements for non-lists

### ISSUE THREAD

**Issue by chasenlehara** [CCALI/a2jdeps#52]
As a screen reader user, I don’t want list elements used for things that are not lists, so that I can understand the document more easily.

Currently, ul/li are used throughout the document for things that are not lists, e.g. the root of the page is a ul of sections.

**Comment by chasenlehara** [comment]
@mikemitchel I want to make sure I don’t miss something you already know about.

Was there a specific reason that ul/li was used here? https://github.com/CCALI/a2jdeps/blob/6907e9d734de6d0df095a63b31143f326f5ffe4c/elements/a2j-template/a2j-template.stache#L9-L11

I am thinking about removing the `ul` and changing the `li` elements to `section` elements.

Obviously there will be some work to get the drag/drop and styles working correctly, but is there anything else I should keep in mind, or a reason why they’re ul/li right now?

**Comment by mitch-mitchel** [comment]
I don't think there was any reason other than `TODO` lists being the sample code for all things CanJS. I think we should make it semantically correct and I can help fix any side effects of these changes if you need my help.
