### ISSUE TITLE
tests fail in firefox 108

### ISSUE THREAD

**Issue by tobiasnteireho** [CCALI/a2jdeps#72]
automated tests that were previously passing are now failing in ff 108. Passes in chrome and safari https://github.com/CCALI/a2jdeps/actions/runs/3906468133/jobs/6674678484

likely related to https://github.com/CCALI/a2jviewer/issues/241 as the failing tests overlap.

**Comment by mitch-mitchel** [comment]
Tests fail when running the entire suite of tests, but pass when running smaller subsets. (see attached gif). Errors in Firefox (ver 109.01 (46-bit on mac) dev console seem like they are mistaking .stache and .less files for XML files - not sure if this is a false flag, or requires some fix. First round of google searches did not give any concrete examples of this happening to anyone else.
<img width="1267" alt="firefox tests pass w xml errors" src="https://user-images.githubusercontent.com/11528248/217964050-ac12ed9c-d9c7-41cd-ac0b-b0c15e031fe6.png">

![firefox tests](https://user-images.githubusercontent.com/11528248/217964096-639b511a-9731-4fe5-bbdf-a25d4225c385.gif)

**Comment by tobiasnteireho** [comment]
tests now pass in firefox 110. https://github.com/CCALI/a2jdeps/actions/runs/4427272839 likely related to https://github.com/CCALI/a2jviewer/issues/241
